//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newDemEx.BaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material()
        {
            this.MaterialInProduct = new HashSet<MaterialInProduct>();
        }
    
        public int Id { get; set; }
        public int MaterialTypeId { get; set; }
        public string Name { get; set; }
        public int ProducerId { get; set; }
        public int UnitId { get; set; }
        public string Description { get; set; }
        public byte[] Photo { get; set; }
        public decimal Cost { get; set; }
    
        public virtual MaterialType MaterialType { get; set; }
        public virtual Producer Producer { get; set; }
        public virtual Unit Unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialInProduct> MaterialInProduct { get; set; }
    }
}
